services:
  postgres:
    restart: always
    # In production, we might not want to expose the DB port to the host
    # ports: !reset [] 
    logging:
      driver: "json-file"
      options:
        max-size: "100mb"
        max-file: "3"

  api:
    restart: always
    environment:
      - APP_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "100mb"
        max-file: "3"
